language: php

php:
    - 5.5
    - 5.6
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

services:
    - mongodb
    - rabbitmq
    - redis-server

before_install:
    - sudo apt-get update
    - composer self-update
    - mysql -e 'CREATE DATABASE certificationy COLLATE utf8_unicode_ci;'

before_script:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "no" | pecl install apcu-beta; fi;'
    - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then
          git clone https://github.com/mongofill/mongofill-hhvm;
          cd mongofill-hhvm;
          /bin/bash tools/travis.sh;
          cd -;
      elif [ "$TRAVIS_PHP_VERSION" == "nightly" ]; then
          yes "\n" | pecl install mongo;
      else
          echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
      fi
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;'
    - COMPOSER_ROOT_VERSION=dev-master MYSQL_USER=travis composer --prefer-source install

script:
    - bin/phpunit -c app --coverage-text
    - echo "Running tests requiring tty"
    - bin/phpunit -c app --group tty

notifications:
    email:
        - johann_27@hotmail.fr
